services:
  influxdb2:
    image: influxdb:2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=health_org
      - DOCKER_INFLUXDB_INIT_BUCKET=health_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN= ${INFLUX_TOKEN}
    volumes:
      - ./.docker/influxdb_data:/var/lib/influxdb2:z
      - ./.docker/influxdb_config:/etc/influxdb2:z

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./.docker/mosquitto.conf:/mosquitto/config/mosquitto.conf:z

volumes:
  influxdb_data:
  influxdb_config: